version: '3'

networks:
  bridge:
    driver: bridge

services:
  app:
    build: .
    depends_on:
      - "database"
      - "ldap"
#      - "cas"
    environment:
      - MYSQL_HOST=database
      - MYSQL_ROOT_PASSWORD=root
      - LDAP_HOST=ldap
    extra_hosts:
      - "comapps.staging:172.30.1.8"
    networks:
      - bridge
    ports:
      - "3000:3000"
    volumes:
      - .:/app

#  cas:
#    build:
#      context: http://dcsgitlab.shef.ac.uk/forks/rbcas-casinoapp-docker.git
#    depends_on:
#      - "ldap"
#    environment:
#      - LDAP_HOST=ldap
#    networks:
#      - bridge
#    ports:
#      - "8181:8181"

  database:
    environment:
      - MYSQL_ROOT_PASSWORD=root
    image: "mariadb:latest"
    networks:
      - bridge
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  ldap:
    image: "greggigon/apacheds"
    networks:
      - bridge
    ports:
      - "10389:10389"

volumes:
  mariadb_data:
